(def _GLUT_DOUBLE 2)
(def _GLUT_RGB 0)
(fun (glutInitDisplayMode mode) (Command 'fbo_impl_glutInitDisplayMode ($ mode)))
(fun (fbo_main0 ) (Command 'fbo_impl_fbo_main0 ($ )))
(fun (fbo_main1 ) (Command 'fbo_impl_fbo_main1 ($ )))
