(fun (id x) x)

(fun (and True True) True)
(fun (and True False) False)
(fun (and False True) False)
(fun (and False False) False)
(fun (or True True) True)
(fun (or False True) True)
(fun (or True False) True)
(fun (or False False) False)
(fun (not True) False)
(fun (not False) True)
