(fun (<= a b) (not (> a b)))
(fun (>= a b) (not (< a b)))
(fun (!= a b) (not (== a b)))
(fun (not 'true) false)
(fun (not 'false) true)
(fun (and 'true 'true) 'true)
(fun (and 'false 'false) 'false)
(fun (and 'true 'false) 'false)
(fun (and 'false 'true) 'false)
