(fun (cons a b) (Cons a b))
(fun (car (Cons a b)) a)
(fun (cdr (Cons a b)) b)
(fun (pair? (Cons a b)) True)
(fun (pair? x) False)

;; ;; (cons 1 2)
;; ;; (car (cons 1 2))
;; ;; (cdr (cons 1 2))

;; ((/. (x) (x 2)) (/. (x) x))
;; (/. (r) r)
;; ((/. (r) r) 3)
;; ((+ 10) 20)
;; ((+ ((/. (x) x) 2000)) 3000)
;; ((== 30) 30)
;; ((== 30) 40)

(cons 1 2)
(car (cons 1 2))
(cdr (cons 1 2))
(pair? (cons 1 2))
(pair? (car (cons 1 2)))
(pair? (cdr (cons 1 2)))
