(ffi "ref")
(ffi "shew")
(fun (main)
     (doo
      ref (create_float_ref poop)
      val (read_float_ref ref)
      _ (shew_float val)
      _ (write_float_ref ref 20)
      val (read_float_ref ref)
      _ (shew_float val)
      _ (destroy_float_ref ref)))

;; (fun (main)
;;      (doo
;;       c (prim_getchar)
;;       c2 (prim_getchar)
;;       dummy (prim_putchar c2)
;;       dummy2 (prim_putchar c)
;;       dummy3 (prim_putchar 10)
;;       ))
