(fun (foo a) (Bar a))
(fun (foo a b) (Boot (foo a) (foo b)))
(fun (zek (Bar (Bar x))) (Shy x))
(fun (foo (Bar a) b) (Book b a))
(fun (het a b) (Yip a b))
(fun (hat (Yip a b)) (Yap b a))
(fun (hick a) (Vot a a))

(foo Ten)
(foo (Bar Ten) Seventy)
(foo (foo Ten))
(zek (foo (foo Ten)))
(hick (foo (foo Yah)))
(Joo (foo (Bar Ten) Seventy))
(hat (het Ten Twenty))
(foo One Two)

(and True True)
(and True False)
(and False True)
(and False False)
(or True True)
(or False True)
(or True False)
(or False False)
(not True)
(not False)

(id True)
(id False)

(if True Ten Twenty)
(if False Ten Twenty)
