(fun (foo a) (Bar a))
(fun (foo a b) (Boot (foo a) (foo b)))
(fun (zek (Bar (Bar x))) (Shy x))
(fun (foo (Bar a) b) (Book b a))
(fun (het a b) (Yip a b))
(fun (hat (Yip a b)) (Yap b a))
(fun (hick a) (Vot a a))

(foo Ten)
(foo (Bar Ten) Seventy)
(foo (foo Ten))
(zek (foo (foo Ten)))
(hick (foo (foo Yah)))
(Joo (foo (Bar Ten) Seventy))
(hat (het Ten Twenty))
(foo One Two)

(and True True)
(and True False)
(and False True)
(and False False)
(or True True)
(or False True)
(or True False)
(or False False)
(not True)
(not False)
(xor True True)
(xor False True)
(xor True False)
(xor False False)

(id True)
(id False)

(if True Ten Twenty)
(if False Ten Twenty)

(append (Cons One (Cons Two Nil)) (Cons Three (Cons Four Nil)))
(reverse (append (Cons One (Cons Two Nil)) (Cons Three (Cons Four Nil))))
(reverse (Cons One (Cons Two (Cons Three (Cons Four Nil)))))
(reverse (reverse (Cons One (Cons Two (Cons Three (Cons Four Nil))))))
(reverse Nil)
(reverse (Cons One Nil))
(append (Cons One Nil) (Cons Two Nil))
(append Nil (Cons One (Cons Two Nil)))
(append (Cons One (Cons Two Nil)) Nil)
(append Nil Nil)

(+ 0 0)
(+ 0 1)
(+ 1 0)
(+ 1 1)
(+ 12 23)
(+ 120 23)
(+ 256 256)
